### ISSUE TITLE
5.2 release checklist

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#528]
# TODO
- [x] deploy marytts artifacts to Bintray
- [x] deploy voice artifacts to Bintray
- [x] update http://mary.dfki.de website
- [x] update http://marytts.github.io website
- [x] rebuild installer
- [x] update demo server
- [x] release
- [x] upload release assets
- [x] announce

## Rebuild unit-selection voices
- German
    - [x] bits1
    - [x] bits2
    - [x] bits3
    - [x] bits4
    - [x] dfki-pavoque-neutral
    - [x] dfki-pavoque-styles
- English
    - [x] cmu-bdl
    - [x] cmu-rms
    - [x] cmu-slt
    - [x] dfki-poppy
    - [x] dfki-prudence
    - [x] dfki-obadiah
    - [x] dfki-spike
- French
    - [x] enst-camille
    - [x] upmc-jessica
    - [x] upmc-pierre
- Other
    - [x] dfki-ot

## Repackage HSMM voices
- German
    - [x] bits1-hsmm
    - [x] bits3-hsmm
    - [x] dfki-pavoque-neutral-hsmm
- English
    - [x] cmu-bdl-hsmm
    - [x] cmu-rms-hsmm
    - [x] dfki-poppy-hsmm
    - [x] dfki-prudence-hsmm
    - [x] dfki-obadiah-hsmm
    - [x] dfki-spike-hsmm
- French
    - [x] enst-camille-hsmm
    - [x] enst-dennys-hsmm
    - [x] upmc-jessica-hsmm
    - [x] upmc-pierre-hsmm
- Other
    - [x] cmu-nk-hsmm
    - [x] dfki-ot-hsmm
    - [x] istc-lucia-hsmm
