### ISSUE TITLE
5.3.0-beta1 Release Checklist

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#924]
- [ ] Ensure minimal JDK version is active
- [ ] Update `CHANGELOG`
- [ ] Increment `project.version` to release
- [ ] Commit to **master**
- [ ] Run `./gradlew clean build`
- [ ] Run `git tag -am'Release v5.3.0-beta1' v5.3.0-beta1
- [ ] Run `./gradlew publishToMavenLocal`
- [ ] In **maven** branches of [marytts-txt2wav](https://github.com/marytts/marytts-txt2wav/blob/gradle), upgrade version of `voice-cmu-slt-hsmm` depenency to `5.3.0-beta1`, then test
- [ ] Do the same for **gradle** branch (add `mavenLocal()` to `repositories`)
- [ ] Run `./gradlew publishToMavenLocal`
- [ ] Login to JCenter, publish artifacts
- [ ] Increment `project.version` to next release with `-SNAPSHOT` suffix
- [ ] Update `CHANGELOG`
- [ ] Commit to **master**
- [ ] Push release tag and **master** to upstream
- [ ] Create new Release on GitHub, paste section from `CHANGELOG`
- [ ] Upload release assets

**Comment by psibre** [comment]
Further updates to voicebuilding plugin, voices, and website...

**Comment by seblemaguer** [comment]
What do you mean by "Ensure minimal JDK version is active"

**Comment by psibre** [comment]
We want to compile on the minimum supported to avoid UnsupportedClassVersionErrors by downstream runtimes. So build the release with Java 8.

On June 28, 2019 12:51:56 PM GMT+02:00, "Sébastien Le Maguer" <notifications@github.com> wrote:
>What do you mean by "Ensure minimal JDK version is active"

--
/**
* Dr. Ingmar Steiner
* Director Process Innovation & Development
*
* audEERING GmbH
* Friedrichshafener Str. 1
* 82205 Gilching
* Germany
*
* @tel: +49-8105-7756150
* @fax: +49-8105-7756152
* @web: https://www.audeering.com/
*
* Registered/Billing address: Landsberger Str. 46d,
* 82205 Gilching, Germany
*
* Amtsgericht: München
* Handelsregister: HRB 203928
* Geschäftsführer: Prof. Dr. Björn Schuller, Dagmar M. Schuller
*
* This message is confidential. It may also be privileged or otherwise
* protected by work product immunity or other legal rules. If you have
* received it by mistake please let us know by reply and then delete it
* from your system; you should not copy it or disclose its contents to
* anyone. All messages sent to and from our company may be monitored to
* ensure compliance with internal policies and to protect our business.
* Emails are not secure and cannot be guaranteed to be error free as
* they can be intercepted, amended, lost or destroyed, or contain
* viruses. Anyone who communicates with us by email is taken to accept
* these risks.
*/

**Comment by kirkmarkarian** [comment]
After much searching, I found this method to try and contact those working on the MaryTTS application.

I love it, use it for various musical projects!  Not being a programmer (not at all a programmer), yet having access to beautiful TTS voices via the CMU Arctic library is great.  Will there be more voices that I can add (US English only) maybe to the 5.2 release, if not the next release?  I have been following along on GitHub, but it’s all in a language that is difficult for me to understand (code-talk).  I also have brain damage from three brain surgeries, so coding/language just doesn’t stick.  

I’m eager to learn more - will there be an updated UI?  Will the next version have a build for each platform, versus java binary files?  Will there be other US English voices?
